name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: golangci/golangci-lint:v1.50.0-alpine
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/check/lint.sh

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: ./scripts/check/unit-test.sh
      - uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_UPLOAD_TOKEN }}
          file: ./.test_coverage.txt
          fail_ci_if_error: false

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    env:
      SLOTH_VERSION: v0.6.0
    steps:
      - uses: actions/checkout@v4
      - name: Execute tests
        run: |
          curl -Lo sloth https://github.com/slok/sloth/releases/download/${SLOTH_VERSION}/sloth-linux-amd64 && chmod +x sloth && sudo mv sloth /usr/local/bin/
          ./scripts/check/integration-test.sh
