name: PR publish

on:
  issue_comment:
    types: [created]
jobs:
  pr-release-images:
    # Only on pull request and `publish`.
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'publish')
    env:
      PROD_IMAGE_NAME: ghcr.io/${GITHUB_REPOSITORY}
      VERSION: pr-${{ github.event.issue.number }}
    name: Release images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Required because issue_comment events are globals.
      # Check: https://github.com/actions/checkout/issues/331
      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hub pr checkout ${{ github.event.issue.number }}
      - name: Docker login
        run: docker login ghcr.io  -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish images
        run: make build-publish-image-all
